INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 9446:
INFO:root:Initial location: 0.0, 0.0, 0.0
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 53, in main
    oscar.navigateMap([0, 0], [4, 1])
  File "/home/pi/oscar/Robot.py", line 107, in navigateMap
    print('next pos is {}'.format(destination))
UnboundLocalError: local variable 'destination' referenced before assignment

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
