INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 11204:
INFO:root:Initial location: 0.2, 1.8, 3.141592653589793
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 57, in main
    oscar.navigateMap([0, 4], [4, 1])
AttributeError: 'Robot' object has no attribute 'navigateMap'

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
