INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 12126:
INFO:root:Initial location: 0.2, 1.8, 3.141592653589793
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 57, in main
    actions.map.navigateMap(oscar, [0, 4], [4, 1])
AttributeError: module 'actions' has no attribute 'map'

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
